#!/bin/sh
### BEGIN INIT INFO
# Provides:          terrible
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: terreria-initscript
# Description:       terrible terreria initscript,
#                    its terrible because windows sucks. windows sucks becuase it does. 
### END INIT INFO

# Author: knope github.com/knope
#

DESC="terrible terreria init script"
terrible_home="/home/terrible/terr/serv"
terrible_executable="${terrible_home}/run_me"
terrible_worlds="/home/terrible/My\ Games/Terraria/Worlds"
terrible_backups="/home/terrible/terr/back"


############
## begin terrible functions
############
### begin terrible user function
#
terrible_user() {
    who_i_be=`(whoami)`
    if [ $who_i_be = terrible ]
    then
        /bin/bash -c "$1"
    else
        echo '        ... '
        echo '        wrong user! do it again!!!!         [-.-]'
    fi
}
#
### end terrible user function
### begin terrible message
#
terrible_message() {
    say="$1"
    if pgrep -u terrible -f run_me > /dev/null
    then
        terrible_user ". ~/.profile ; screen -p 0 -s terriblescreenisnot -X eval 'stuff \"${say}\"\015'"
    else
        echo 'bad, go try when the server is actually running you twit, :P'
    fi
}
#
### end terrible message
### begin terrible start function
#
terrible_start() {
    if pgrep -u terrible -f run_me > /dev/null
    then
        echo '        the terrible server is running already!  [-.-]'
    else
        echo '        o look at you trying to start the server and stuff   [-.-]'
        echo "            i suppose we'll start now..."
        terrible_user ". ~/.profile ; cd ~terrible/terr/serv ; screen -dms terriblescreenisnot ./run_me"
        sleep 2
        terrible_message "1"
        sleep 1
        terrible_message "42"
        sleep 1
        terrible_message "7777"
        sleep 1
        if pgrep -u terrible -f run_me > /dev/null
        then
            echo '        wooo server started... give it time to set liquids and crap'
            echo '                 maybe like... 2 mins'
        else
            echo ' holy un-error-cal errors BatMan, something went shitty'
            echo '      read logs peon...  v  '
            tail -n 12 ${terrible_home}/ServerLog.txt
            echo '      read logs peon...  ^  '
        fi
    fi
}
#
### end terrible start function
### begin terrible stop function
#
terrible_stop() {
    if pgrep -u terrible -f run_me > /dev/null
    then
        echo '            terrible server is running, stopping in 15 seconds'
        terrible_message "say stopping in 15 seconds"
        sleep 5
        terrible_message "say stopping in 10 seconds"
        sleep 5
        terrible_message "say this terrible server is stopping in 5"
        sleep 1
        terrible_message "say 4 seconds"
        sleep 2
        terrible_message "say 2 ... "
        sleep 1
        terrible_message "say  ... 1... ttyl  :)"
        sleep 1
        terrible_message "off"
        echo '            server is now closing'
    else
        echo "            the damn server isn't even running..."
        echo "            how the hell do you expect it to stop running?.. o.O"
    fi
}
#
### end terrible stop function
### begin terrible backup function
#
terrible_backup() {
    back_up_file="/home/terrible/terr/back/wads/scarcityfree-terraria.`(date +"%y%m%d_%T")`"
    if pgrep -u terrible -f run_me > /dev/null
    then
        echo "not safe, server still running"
    else
        rsync -a /home/terrible/terr/serv /home/terrible/terr/back/stage/
        rsync -a /home/terrible/My\ Games/Terraria /home/terrible/terr/back/stage/
        echo "stage for:" |tee /home/terrible/terr/back/stage/backup_info
        echo "${back_up_file}" |tee -a /home/terrible/terr/back/stage/backup_info
        cp /home/terrible/terr/back/stage/backup_info /home/terrible/terr/back/backup_last_info
        tar -czvf "${back_up_file}" /home/terrible/terr/back/stage/*
    fi
}
#
### end terrible backup function

############
## end terrible functions
############

case $1 in
    status)
        if pgrep -u terrible -f run_me > /dev/null
        then
            echo 'terrible server is running'
        else
            echo 'terrible server is not running'
        fi
        ;;
    stop)
        terrible_stop
        ;;
    start)
        terrible_start
        ;;
    restart)
        terrible_message "say the server is restarting... go have some coffee, or run a lap around your neighborhood"
        terrible_message "say be back online in about 5 mins, tops"
        terrible_stop
        sleep 45
        terrible_start
        ;;
    backup)
        terrible_message "shutting down to take a nice clean backup..."
        terrible_message "say be back online in about 5 mins, tops"
        terrible_stop
        sleep 45
        terrible_backup
        terrible_start
        ;;
    msg | message | say)
        terrible_message "say $1"
        ;;
    *)
        echo "wrong, try again"
        ;;
esac
